logging:
  level:
    root: error
    org.springframework.security: debug

server:
  port: 8001

spring:
  datasource:
    driverclassname: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://127.0.0.1:5005/streamdata
    username:
    password:
    type: org.hsqldb.jdbc.JDBCDataSource
  activemq:
    pool:
      enabled: off

streamdata:
  oauth-server:
    token:
      access-validity-seconds: 600
      refresh-validity-seconds: 600
    jwk:
      keystore-location: oauth2-server.jks
      keystore-alias: oauth2-server-alias
      keystore-password: htb98980