logging:
  level:
    root: error
    org.springframework.security: debug

server:
  port: 8001

spring:
  datasource:
    driverclassname: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://127.0.0.1:5005/maindb
    username:
    password:
    type: org.hsqldb.jdbc.JDBCDataSource


oauth-srv:
  accessTokenValiditySeconds: 1800

