logging:
  level:
    root: error
    org.springframework.security: debug

server:
  port: 8001

spring:
  datasource:
    driverclassname: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://127.0.0.1:5005/streamdata
    username:
    password:
    type: org.hsqldb.jdbc.JDBCDataSource


streamdata:
  oauth-server:
    access-token-validity-seconds: 600

