INSERT INTO USER (USERNAME,PASSWORD, EXPIRED, LOCKED,  CREATED_BY_ID, LAST_MODIFIED_BY_ID, CREATED_DATE, LAST_MODIFIED_DATE)
    VALUES ('admin','$2a$10$gNoqkNCcZ.nlp/zUdgLqHuGp9FWJKDbu5orXwTuCZFNsSMyY89gcq',0,0,1,1,current_date,current_date);

insert into GENDER(id,code,title)values (1,'M','Male');
insert into GENDER(id,code,title)values (2,'F','Female');

INSERT INTO PRIMITIVE_DATA_TYPE(ID,CODE,TITLE)VALUES (1,'BOOLEAN','Boolean');
INSERT INTO PRIMITIVE_DATA_TYPE(ID,CODE,TITLE)VALUES (2,'NUMBER','Number');
INSERT INTO PRIMITIVE_DATA_TYPE(ID,CODE,TITLE)VALUES (3,'STRING','String');
INSERT INTO PRIMITIVE_DATA_TYPE(ID,CODE,TITLE)VALUES (4,'ARRAY','Array');

insert into OBJECT_DEFINITION(ID,NAME,TITLE,CREATED_BY_ID,LAST_MODIFIED_BY_ID,CREATED_DATE,LAST_MODIFIED_DATE)
values (1,'Person','Person Info',1,1,current_date,current_date);

insert into PROPERTY_DEFINITION(ID,NAME,TITLE,DATA_TYPE_ID,OBJECT_DEFINITION_ID)
values (1,'firstName','lastName',3,1);

insert into PROPERTY_DEFINITION(ID,NAME,TITLE,DATA_TYPE_ID,OBJECT_DEFINITION_ID)
values (2,'lastName','lastName',3,1);

insert into PROPERTY_DEFINITION(ID,NAME,TITLE,DATA_TYPE_ID,OBJECT_DEFINITION_ID)
values (3,'nationalCode','nationalCode',3,1);
