INSERT INTO PUBLIC.USER (USERNAME,PASSWORD, EXPIRED, LOCKED,  CREATED_BY_ID, LAST_MODIFIED_BY_ID, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('admin','$2a$10$NgFTcxZUn9h8oQZUtOpUYetQlEUAw0TrjVbEcaOeftrCTtr.e58E6',0,0,1,1,current_date,current_date);
INSERT INTO PUBLIC.ACCOUNT (NAME, BALANCE, CREATED_BY_ID, LAST_MODIFIED_BY_ID, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('ansar-bank-account', 100000000, 1, 1,current_date,current_date);
INSERT INTO PUBLIC.ACCOUNT (NAME, BALANCE, CREATED_BY_ID, LAST_MODIFIED_BY_ID, CREATED_DATE, LAST_MODIFIED_DATE) VALUES ('meli-bank-account', 1000, 1, 1,current_date,current_date);
INSERT INTO PUBLIC.TRANSACTION_TYPE (ID,CODE, TITLE) VALUES (1,'INCOME','INCOME');
INSERT INTO PUBLIC.TRANSACTION_TYPE (ID,CODE, TITLE) VALUES (2,'EXPENSE','EXPENSE');

INSERT INTO PUBLIC.TRANSACTION (ACCOUNT_ID, TRANSACTION_TYPE_ID, TRANSACTION_AMOUNT, TRANSACTION_DATE, DESCRIPTION,
                                CREATED_BY_ID, LAST_MODIFIED_BY_ID, CREATED_DATE, LAST_MODIFIED_DATE)
VALUES (1, 1, 100000000, current_date, 'T-1', 1, 1, current_date, current_date);

insert into PUBLIC.GENDER(id,code,title)values (1,'M','MALE');
insert into PUBLIC.GENDER(id,code,title)values (2,'F','FEMALE');